development:
  adapter: postgresql
  encoding: unicode
  database: solutionsfuse_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: solutionsfuse_test
  pool: 5
  host: localhost